# Generated by Django 4.2.3 on 2023-10-19 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('prestamo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_cuotas', models.PositiveIntegerField()),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.cliente')),
            ],
        ),
    ]
