# Generated by Django 4.2.3 on 2023-10-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0002_abono'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='valor_cuota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='debe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
