# Generated by Django 4.2.3 on 2023-11-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0004_alter_prestamo_tasa_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_cuota',
            field=models.DateField(default='2001-12-22'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='frecuencia_pago',
            field=models.CharField(default='diario', max_length=10),
        ),
    ]
