# Generated by Django 4.2.3 on 2023-11-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0005_prestamo_fecha_cuota_prestamo_frecuencia_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_cuota',
            field=models.DateField(blank=True, null=True),
        ),
    ]
