# Generated by Django 4.2.3 on 2023-11-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0009_alter_prestamo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
