# Generated by Django 4.2.3 on 2023-11-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0010_alter_prestamo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(default='Debe', max_length=10),
        ),
    ]
