# Generated by Django 4.2.3 on 2023-11-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0011_alter_prestamo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='frecuencia_pago',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
