# Generated by Django 4.2.3 on 2023-12-06 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0013_remove_prestamo_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='prestamo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='prestamo.prestamo'),
        ),
    ]
