# Generated by Django 4.2.3 on 2023-12-06 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0014_abono_prestamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abono',
            name='prestamo',
        ),
    ]
